name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=22.0
  - numpy
  - joblib
  - tqdm
  - matplotlib
  - h5py
  - pandas
  - scikit-learn
  - networkx
  - hdbscan
  - numba
  - jupyter
  - pyqt=5
  - pyqtgraph
  - pip:
    - spikeinterface[full,widgets]>=0.99
    - spikeinterface-gui>=0.7
    - docker
    # - phy==2.0b5
